--
--! @file constants.vhd
--! @brief Hermes generic NoC with output buffers constant files.
--! @details This **should** be automatic generated by Atlas.
--! @author Angelo Elias Dalzotto (angelo.dalzotto@edu.pucrs.br)
--! @author Nicolas Lodea (nicolas.lodea@edu.pucrs.br)
--! @date 2020/04
-- 

library ieee;
use ieee.std_logic_1164.all;

package constants is
	--! NoC Size
	constant X_SIZE : integer := 3;
	constant Y_SIZE : integer := 3;

	--! Channel width, also the flit width
	constant FLIT_SIZE : integer range 1 to 64 := 16;

	--! Number of buffer slots for each output buffer
	constant BUFFER_SIZE: integer := 4;

end package;